# Generated by Django 5.0.4 on 2024-04-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
