# Generated by Django 5.0.4 on 2024-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0010_healthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='calories',
            field=models.FloatField(),
        ),
    ]
