# Generated by Django 5.0.4 on 2024-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0011_alter_healthdata_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='steps',
            field=models.FloatField(),
        ),
    ]
